"""existing schema baseline

Revision ID: 0001_existing_schema_baseline
Revises:
"""
from alembic import op
import sqlalchemy as sa


revision = "0001_existing_schema_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("user_accounts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("username", sa.String(64), nullable=False, unique=True), sa.Column("display_name", sa.String(128), nullable=False), sa.Column("password_hash", sa.String(128), nullable=False), sa.Column("roles_csv", sa.String(256), nullable=False, server_default="ROLE_USER"), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("chat_sessions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("public_id", sa.String(64), nullable=False, unique=True), sa.Column("title", sa.String(160), nullable=False), sa.Column("user_id", sa.Integer(), sa.ForeignKey("user_accounts.id"), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("chat_messages", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("user_accounts.id"), nullable=False), sa.Column("session_id", sa.Integer(), sa.ForeignKey("chat_sessions.id"), nullable=False), sa.Column("role", sa.String(32), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("knowledge_chunks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("source", sa.String(256), nullable=False), sa.Column("source_index", sa.Integer(), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("embedding_json", sa.Text(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("psychological_reports", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("user_accounts.id"), nullable=False), sa.Column("session_id", sa.Integer(), sa.ForeignKey("chat_sessions.id"), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("intent", sa.String(32), nullable=False), sa.Column("emotion", sa.String(32), nullable=False), sa.Column("emotion_score", sa.Float(), nullable=False), sa.Column("risk_level", sa.String(32), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("summary", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("risk_cases", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("report_id", sa.Integer(), nullable=False, unique=True), sa.Column("risk_level", sa.String(32), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("owner", sa.String(128), nullable=False, server_default="unassigned"), sa.Column("summary", sa.Text(), nullable=False), sa.Column("handoff_summary", sa.Text(), nullable=False), sa.Column("acknowledged_by", sa.String(128), nullable=True), sa.Column("acknowledged_at", sa.DateTime(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("case_notes", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("case_id", sa.Integer(), nullable=False), sa.Column("actor", sa.String(128), nullable=False), sa.Column("note", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("alert_records", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("report_id", sa.Integer(), nullable=False), sa.Column("channel", sa.String(64), nullable=False), sa.Column("recipient", sa.String(256), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("excel_records", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("report_id", sa.Integer(), nullable=False), sa.Column("file_path", sa.String(512), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("tool_jobs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("report_id", sa.Integer(), nullable=False), sa.Column("kind", sa.String(64), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"), sa.Column("max_attempts", sa.Integer(), nullable=False, server_default="3"), sa.Column("depends_on_job_id", sa.Integer(), nullable=True), sa.Column("run_after", sa.DateTime(), nullable=False), sa.Column("last_error", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("dead_letter_records", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("job_id", sa.Integer(), nullable=True), sa.Column("report_id", sa.Integer(), nullable=False), sa.Column("kind", sa.String(64), nullable=False), sa.Column("reason", sa.Text(), nullable=False), sa.Column("payload", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("agent_run_traces", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("user_accounts.id"), nullable=False), sa.Column("session_id", sa.Integer(), sa.ForeignKey("chat_sessions.id"), nullable=False), sa.Column("report_id", sa.Integer(), nullable=True), sa.Column("intent", sa.String(32), nullable=False, ), sa.Column("risk_level", sa.String(32), nullable=False, server_default="LOW"), sa.Column("original_input", sa.Text(), nullable=False), sa.Column("sanitized_input", sa.Text(), nullable=False), sa.Column("memory_brief", sa.Text(), nullable=False), sa.Column("agent_steps_json", sa.Text(), nullable=False), sa.Column("retrieved_knowledge_json", sa.Text(), nullable=False), sa.Column("response_messages_json", sa.Text(), nullable=False), sa.Column("assessment_json", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("tool_audit_records", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("job_id", sa.Integer(), nullable=True), sa.Column("report_id", sa.Integer(), nullable=True), sa.Column("tool_name", sa.String(64), nullable=False), sa.Column("policy", sa.String(128), nullable=False, server_default=""), sa.Column("allowed", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("status", sa.String(32), nullable=False), sa.Column("reason", sa.Text(), nullable=False), sa.Column("payload", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))


def downgrade() -> None:
    raise RuntimeError("baseline migration is intentionally irreversible")
